// This file is auto-generated by @hey-api/openapi-ts

import { type Options, usersLoginForAccessToken, usersRegister, usersLogin, usersCheckLogin, usersLogout, meetingsStartMeeting, meetingsJoinMeeting, meetingsEndMeeting, meetingsLeaveMeeting, meetingsRequestTotal, meetingsChangeTitle, meetingsUpdateHotWords, meetingsManualUpdate, meetingsChooseNode, meetingsModifyNode, meetingsAddNode, meetingsDeleteNode, meetingsSendUserSummary, meetingsGetAllMeetings, meetingsGetOngoingMeetings, meetingsRequestRecord, meetingsDownloadAudio, meetingsGetAudio } from '../sdk.gen';
import { queryOptions, type UseMutationOptions, infiniteQueryOptions, type InfiniteData } from '@tanstack/react-query';
import type { UsersLoginForAccessTokenData, UsersLoginForAccessTokenError, UsersLoginForAccessTokenResponse, UsersRegisterData, UsersRegisterError, UsersRegisterResponse, UsersLoginData, UsersLoginError, UsersLoginResponse, UsersCheckLoginData, UsersCheckLoginError, UsersCheckLoginResponse, UsersLogoutData, UsersLogoutError, UsersLogoutResponse, MeetingsStartMeetingData, MeetingsStartMeetingError, MeetingsStartMeetingResponse, MeetingsJoinMeetingData, MeetingsJoinMeetingError, MeetingsJoinMeetingResponse, MeetingsEndMeetingData, MeetingsEndMeetingError, MeetingsEndMeetingResponse, MeetingsLeaveMeetingData, MeetingsLeaveMeetingError, MeetingsLeaveMeetingResponse, MeetingsRequestTotalData, MeetingsRequestTotalError, MeetingsRequestTotalResponse, MeetingsChangeTitleData, MeetingsChangeTitleError, MeetingsChangeTitleResponse, MeetingsUpdateHotWordsData, MeetingsUpdateHotWordsError, MeetingsUpdateHotWordsResponse, MeetingsManualUpdateData, MeetingsManualUpdateError, MeetingsManualUpdateResponse, MeetingsChooseNodeData, MeetingsChooseNodeError, MeetingsChooseNodeResponse, MeetingsModifyNodeData, MeetingsModifyNodeError, MeetingsModifyNodeResponse, MeetingsAddNodeData, MeetingsAddNodeError, MeetingsAddNodeResponse, MeetingsDeleteNodeData, MeetingsDeleteNodeError, MeetingsDeleteNodeResponse, MeetingsSendUserSummaryData, MeetingsSendUserSummaryError, MeetingsSendUserSummaryResponse, MeetingsGetAllMeetingsData, MeetingsGetAllMeetingsError, MeetingsGetAllMeetingsResponse, MeetingsGetOngoingMeetingsData, MeetingsRequestRecordData, MeetingsRequestRecordError, MeetingsRequestRecordResponse, MeetingsDownloadAudioData, MeetingsGetAudioData } from '../types.gen';
import { client as _heyApiClient } from '../client.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? _heyApiClient).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [
        params
    ];
};

export const usersLoginForAccessTokenQueryKey = (options: Options<UsersLoginForAccessTokenData>) => createQueryKey('usersLoginForAccessToken', options);

/**
 * Login For Access Token
 */
export const usersLoginForAccessTokenOptions = (options: Options<UsersLoginForAccessTokenData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await usersLoginForAccessToken({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: usersLoginForAccessTokenQueryKey(options)
    });
};

/**
 * Login For Access Token
 */
export const usersLoginForAccessTokenMutation = (options?: Partial<Options<UsersLoginForAccessTokenData>>): UseMutationOptions<UsersLoginForAccessTokenResponse, UsersLoginForAccessTokenError, Options<UsersLoginForAccessTokenData>> => {
    const mutationOptions: UseMutationOptions<UsersLoginForAccessTokenResponse, UsersLoginForAccessTokenError, Options<UsersLoginForAccessTokenData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await usersLoginForAccessToken({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const usersRegisterQueryKey = (options: Options<UsersRegisterData>) => createQueryKey('usersRegister', options);

/**
 * Register
 */
export const usersRegisterOptions = (options: Options<UsersRegisterData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await usersRegister({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: usersRegisterQueryKey(options)
    });
};

/**
 * Register
 */
export const usersRegisterMutation = (options?: Partial<Options<UsersRegisterData>>): UseMutationOptions<UsersRegisterResponse, UsersRegisterError, Options<UsersRegisterData>> => {
    const mutationOptions: UseMutationOptions<UsersRegisterResponse, UsersRegisterError, Options<UsersRegisterData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await usersRegister({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const usersLoginQueryKey = (options: Options<UsersLoginData>) => createQueryKey('usersLogin', options);

/**
 * Login
 */
export const usersLoginOptions = (options: Options<UsersLoginData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await usersLogin({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: usersLoginQueryKey(options)
    });
};

/**
 * Login
 */
export const usersLoginMutation = (options?: Partial<Options<UsersLoginData>>): UseMutationOptions<UsersLoginResponse, UsersLoginError, Options<UsersLoginData>> => {
    const mutationOptions: UseMutationOptions<UsersLoginResponse, UsersLoginError, Options<UsersLoginData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await usersLogin({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const usersCheckLoginQueryKey = (options?: Options<UsersCheckLoginData>) => createQueryKey('usersCheckLogin', options);

/**
 * Check Login
 */
export const usersCheckLoginOptions = (options?: Options<UsersCheckLoginData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await usersCheckLogin({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: usersCheckLoginQueryKey(options)
    });
};

/**
 * Check Login
 */
export const usersCheckLoginMutation = (options?: Partial<Options<UsersCheckLoginData>>): UseMutationOptions<UsersCheckLoginResponse, UsersCheckLoginError, Options<UsersCheckLoginData>> => {
    const mutationOptions: UseMutationOptions<UsersCheckLoginResponse, UsersCheckLoginError, Options<UsersCheckLoginData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await usersCheckLogin({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const usersLogoutQueryKey = (options?: Options<UsersLogoutData>) => createQueryKey('usersLogout', options);

/**
 * Logout
 */
export const usersLogoutOptions = (options?: Options<UsersLogoutData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await usersLogout({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: usersLogoutQueryKey(options)
    });
};

/**
 * Logout
 */
export const usersLogoutMutation = (options?: Partial<Options<UsersLogoutData>>): UseMutationOptions<UsersLogoutResponse, UsersLogoutError, Options<UsersLogoutData>> => {
    const mutationOptions: UseMutationOptions<UsersLogoutResponse, UsersLogoutError, Options<UsersLogoutData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await usersLogout({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const meetingsStartMeetingQueryKey = (options: Options<MeetingsStartMeetingData>) => createQueryKey('meetingsStartMeeting', options);

/**
 * Start Meeting
 */
export const meetingsStartMeetingOptions = (options: Options<MeetingsStartMeetingData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await meetingsStartMeeting({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: meetingsStartMeetingQueryKey(options)
    });
};

/**
 * Start Meeting
 */
export const meetingsStartMeetingMutation = (options?: Partial<Options<MeetingsStartMeetingData>>): UseMutationOptions<MeetingsStartMeetingResponse, MeetingsStartMeetingError, Options<MeetingsStartMeetingData>> => {
    const mutationOptions: UseMutationOptions<MeetingsStartMeetingResponse, MeetingsStartMeetingError, Options<MeetingsStartMeetingData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await meetingsStartMeeting({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const meetingsJoinMeetingQueryKey = (options: Options<MeetingsJoinMeetingData>) => createQueryKey('meetingsJoinMeeting', options);

/**
 * Join Meeting
 */
export const meetingsJoinMeetingOptions = (options: Options<MeetingsJoinMeetingData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await meetingsJoinMeeting({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: meetingsJoinMeetingQueryKey(options)
    });
};

/**
 * Join Meeting
 */
export const meetingsJoinMeetingMutation = (options?: Partial<Options<MeetingsJoinMeetingData>>): UseMutationOptions<MeetingsJoinMeetingResponse, MeetingsJoinMeetingError, Options<MeetingsJoinMeetingData>> => {
    const mutationOptions: UseMutationOptions<MeetingsJoinMeetingResponse, MeetingsJoinMeetingError, Options<MeetingsJoinMeetingData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await meetingsJoinMeeting({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const meetingsEndMeetingQueryKey = (options?: Options<MeetingsEndMeetingData>) => createQueryKey('meetingsEndMeeting', options);

/**
 * End Meeting
 */
export const meetingsEndMeetingOptions = (options?: Options<MeetingsEndMeetingData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await meetingsEndMeeting({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: meetingsEndMeetingQueryKey(options)
    });
};

/**
 * End Meeting
 */
export const meetingsEndMeetingMutation = (options?: Partial<Options<MeetingsEndMeetingData>>): UseMutationOptions<MeetingsEndMeetingResponse, MeetingsEndMeetingError, Options<MeetingsEndMeetingData>> => {
    const mutationOptions: UseMutationOptions<MeetingsEndMeetingResponse, MeetingsEndMeetingError, Options<MeetingsEndMeetingData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await meetingsEndMeeting({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const meetingsLeaveMeetingQueryKey = (options?: Options<MeetingsLeaveMeetingData>) => createQueryKey('meetingsLeaveMeeting', options);

/**
 * Leave Meeting
 */
export const meetingsLeaveMeetingOptions = (options?: Options<MeetingsLeaveMeetingData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await meetingsLeaveMeeting({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: meetingsLeaveMeetingQueryKey(options)
    });
};

/**
 * Leave Meeting
 */
export const meetingsLeaveMeetingMutation = (options?: Partial<Options<MeetingsLeaveMeetingData>>): UseMutationOptions<MeetingsLeaveMeetingResponse, MeetingsLeaveMeetingError, Options<MeetingsLeaveMeetingData>> => {
    const mutationOptions: UseMutationOptions<MeetingsLeaveMeetingResponse, MeetingsLeaveMeetingError, Options<MeetingsLeaveMeetingData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await meetingsLeaveMeeting({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const meetingsRequestTotalQueryKey = (options?: Options<MeetingsRequestTotalData>) => createQueryKey('meetingsRequestTotal', options);

/**
 * Request Total
 */
export const meetingsRequestTotalOptions = (options?: Options<MeetingsRequestTotalData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await meetingsRequestTotal({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: meetingsRequestTotalQueryKey(options)
    });
};

/**
 * Request Total
 */
export const meetingsRequestTotalMutation = (options?: Partial<Options<MeetingsRequestTotalData>>): UseMutationOptions<MeetingsRequestTotalResponse, MeetingsRequestTotalError, Options<MeetingsRequestTotalData>> => {
    const mutationOptions: UseMutationOptions<MeetingsRequestTotalResponse, MeetingsRequestTotalError, Options<MeetingsRequestTotalData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await meetingsRequestTotal({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const meetingsChangeTitleQueryKey = (options: Options<MeetingsChangeTitleData>) => createQueryKey('meetingsChangeTitle', options);

/**
 * Change Title
 */
export const meetingsChangeTitleOptions = (options: Options<MeetingsChangeTitleData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await meetingsChangeTitle({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: meetingsChangeTitleQueryKey(options)
    });
};

/**
 * Change Title
 */
export const meetingsChangeTitleMutation = (options?: Partial<Options<MeetingsChangeTitleData>>): UseMutationOptions<MeetingsChangeTitleResponse, MeetingsChangeTitleError, Options<MeetingsChangeTitleData>> => {
    const mutationOptions: UseMutationOptions<MeetingsChangeTitleResponse, MeetingsChangeTitleError, Options<MeetingsChangeTitleData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await meetingsChangeTitle({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const meetingsUpdateHotWordsQueryKey = (options: Options<MeetingsUpdateHotWordsData>) => createQueryKey('meetingsUpdateHotWords', options);

/**
 * Update Hot Words
 */
export const meetingsUpdateHotWordsOptions = (options: Options<MeetingsUpdateHotWordsData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await meetingsUpdateHotWords({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: meetingsUpdateHotWordsQueryKey(options)
    });
};

/**
 * Update Hot Words
 */
export const meetingsUpdateHotWordsMutation = (options?: Partial<Options<MeetingsUpdateHotWordsData>>): UseMutationOptions<MeetingsUpdateHotWordsResponse, MeetingsUpdateHotWordsError, Options<MeetingsUpdateHotWordsData>> => {
    const mutationOptions: UseMutationOptions<MeetingsUpdateHotWordsResponse, MeetingsUpdateHotWordsError, Options<MeetingsUpdateHotWordsData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await meetingsUpdateHotWords({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const meetingsManualUpdateQueryKey = (options?: Options<MeetingsManualUpdateData>) => createQueryKey('meetingsManualUpdate', options);

/**
 * Manual Update
 */
export const meetingsManualUpdateOptions = (options?: Options<MeetingsManualUpdateData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await meetingsManualUpdate({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: meetingsManualUpdateQueryKey(options)
    });
};

/**
 * Manual Update
 */
export const meetingsManualUpdateMutation = (options?: Partial<Options<MeetingsManualUpdateData>>): UseMutationOptions<MeetingsManualUpdateResponse, MeetingsManualUpdateError, Options<MeetingsManualUpdateData>> => {
    const mutationOptions: UseMutationOptions<MeetingsManualUpdateResponse, MeetingsManualUpdateError, Options<MeetingsManualUpdateData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await meetingsManualUpdate({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const meetingsChooseNodeQueryKey = (options: Options<MeetingsChooseNodeData>) => createQueryKey('meetingsChooseNode', options);

/**
 * Choose Node
 * {
 * "chosenNodeId": "full id"
 * "meeting_hash_id": "hash id",
 * }
 */
export const meetingsChooseNodeOptions = (options: Options<MeetingsChooseNodeData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await meetingsChooseNode({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: meetingsChooseNodeQueryKey(options)
    });
};

/**
 * Choose Node
 * {
 * "chosenNodeId": "full id"
 * "meeting_hash_id": "hash id",
 * }
 */
export const meetingsChooseNodeMutation = (options?: Partial<Options<MeetingsChooseNodeData>>): UseMutationOptions<MeetingsChooseNodeResponse, MeetingsChooseNodeError, Options<MeetingsChooseNodeData>> => {
    const mutationOptions: UseMutationOptions<MeetingsChooseNodeResponse, MeetingsChooseNodeError, Options<MeetingsChooseNodeData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await meetingsChooseNode({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const meetingsModifyNodeQueryKey = (options: Options<MeetingsModifyNodeData>) => createQueryKey('meetingsModifyNode', options);

/**
 * Modify Node
 * 前端->后端：
 * {
 * "meeting_hash_id": str,
 * "full_id": str,
 * "content": str
 * }
 */
export const meetingsModifyNodeOptions = (options: Options<MeetingsModifyNodeData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await meetingsModifyNode({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: meetingsModifyNodeQueryKey(options)
    });
};

/**
 * Modify Node
 * 前端->后端：
 * {
 * "meeting_hash_id": str,
 * "full_id": str,
 * "content": str
 * }
 */
export const meetingsModifyNodeMutation = (options?: Partial<Options<MeetingsModifyNodeData>>): UseMutationOptions<MeetingsModifyNodeResponse, MeetingsModifyNodeError, Options<MeetingsModifyNodeData>> => {
    const mutationOptions: UseMutationOptions<MeetingsModifyNodeResponse, MeetingsModifyNodeError, Options<MeetingsModifyNodeData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await meetingsModifyNode({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const meetingsAddNodeQueryKey = (options: Options<MeetingsAddNodeData>) => createQueryKey('meetingsAddNode', options);

/**
 * Add Node
 * 前端
 * {
 * "type": "ISSUE" / "POSITION",
 * "father_id": "父节点的full id",
 * "content": "",
 * "meeting_hash_id": "",
 * "suggestion_id": ""
 * }
 * 后端
 * {
 * "code": 0,
 * "full_id": "这个节点的full id"
 * }
 */
export const meetingsAddNodeOptions = (options: Options<MeetingsAddNodeData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await meetingsAddNode({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: meetingsAddNodeQueryKey(options)
    });
};

/**
 * Add Node
 * 前端
 * {
 * "type": "ISSUE" / "POSITION",
 * "father_id": "父节点的full id",
 * "content": "",
 * "meeting_hash_id": "",
 * "suggestion_id": ""
 * }
 * 后端
 * {
 * "code": 0,
 * "full_id": "这个节点的full id"
 * }
 */
export const meetingsAddNodeMutation = (options?: Partial<Options<MeetingsAddNodeData>>): UseMutationOptions<MeetingsAddNodeResponse, MeetingsAddNodeError, Options<MeetingsAddNodeData>> => {
    const mutationOptions: UseMutationOptions<MeetingsAddNodeResponse, MeetingsAddNodeError, Options<MeetingsAddNodeData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await meetingsAddNode({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const meetingsDeleteNodeQueryKey = (options: Options<MeetingsDeleteNodeData>) => createQueryKey('meetingsDeleteNode', options);

/**
 * Delete Node
 * 前端
 * {
 * "full_id": "",  # issue/position的full id
 * "meeting_hash_id": ""
 * }
 */
export const meetingsDeleteNodeOptions = (options: Options<MeetingsDeleteNodeData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await meetingsDeleteNode({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: meetingsDeleteNodeQueryKey(options)
    });
};

/**
 * Delete Node
 * 前端
 * {
 * "full_id": "",  # issue/position的full id
 * "meeting_hash_id": ""
 * }
 */
export const meetingsDeleteNodeMutation = (options?: Partial<Options<MeetingsDeleteNodeData>>): UseMutationOptions<MeetingsDeleteNodeResponse, MeetingsDeleteNodeError, Options<MeetingsDeleteNodeData>> => {
    const mutationOptions: UseMutationOptions<MeetingsDeleteNodeResponse, MeetingsDeleteNodeError, Options<MeetingsDeleteNodeData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await meetingsDeleteNode({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const meetingsSendUserSummaryQueryKey = (options: Options<MeetingsSendUserSummaryData>) => createQueryKey('meetingsSendUserSummary', options);

/**
 * Send User Summary
 * {
 * "meeting_hash_id": "hash id",
 * "edit_history": "list"
 * }
 */
export const meetingsSendUserSummaryOptions = (options: Options<MeetingsSendUserSummaryData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await meetingsSendUserSummary({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: meetingsSendUserSummaryQueryKey(options)
    });
};

/**
 * Send User Summary
 * {
 * "meeting_hash_id": "hash id",
 * "edit_history": "list"
 * }
 */
export const meetingsSendUserSummaryMutation = (options?: Partial<Options<MeetingsSendUserSummaryData>>): UseMutationOptions<MeetingsSendUserSummaryResponse, MeetingsSendUserSummaryError, Options<MeetingsSendUserSummaryData>> => {
    const mutationOptions: UseMutationOptions<MeetingsSendUserSummaryResponse, MeetingsSendUserSummaryError, Options<MeetingsSendUserSummaryData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await meetingsSendUserSummary({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const meetingsGetAllMeetingsQueryKey = (options?: Options<MeetingsGetAllMeetingsData>) => createQueryKey('meetingsGetAllMeetings', options);

/**
 * Get All Meetings
 * 输入
 * {
 * hash_id: hash_id,
 * title: title,
 * start_time: startTime,
 * }
 * 输出
 * type MeetingItem = {
 * id: number;
 * hash_id: number;
 * topic: string;
 * created_by: string;
 * created_time: string;
 * status: string;
 * master: string;
 * hot_words: string;
 * anlysisStatus: string;
 * };
 */
export const meetingsGetAllMeetingsOptions = (options?: Options<MeetingsGetAllMeetingsData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await meetingsGetAllMeetings({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: meetingsGetAllMeetingsQueryKey(options)
    });
};

const createInfiniteParams = <K extends Pick<QueryKey<Options>[0], 'body' | 'headers' | 'path' | 'query'>>(queryKey: QueryKey<Options>, page: K) => {
    const params = {
        ...queryKey[0]
    };
    if (page.body) {
        params.body = {
            ...queryKey[0].body as any,
            ...page.body as any
        };
    }
    if (page.headers) {
        params.headers = {
            ...queryKey[0].headers,
            ...page.headers
        };
    }
    if (page.path) {
        params.path = {
            ...queryKey[0].path as any,
            ...page.path as any
        };
    }
    if (page.query) {
        params.query = {
            ...queryKey[0].query as any,
            ...page.query as any
        };
    }
    return params as unknown as typeof page;
};

export const meetingsGetAllMeetingsInfiniteQueryKey = (options?: Options<MeetingsGetAllMeetingsData>): QueryKey<Options<MeetingsGetAllMeetingsData>> => createQueryKey('meetingsGetAllMeetings', options, true);

/**
 * Get All Meetings
 * 输入
 * {
 * hash_id: hash_id,
 * title: title,
 * start_time: startTime,
 * }
 * 输出
 * type MeetingItem = {
 * id: number;
 * hash_id: number;
 * topic: string;
 * created_by: string;
 * created_time: string;
 * status: string;
 * master: string;
 * hot_words: string;
 * anlysisStatus: string;
 * };
 */
export const meetingsGetAllMeetingsInfiniteOptions = (options?: Options<MeetingsGetAllMeetingsData>) => {
    return infiniteQueryOptions<MeetingsGetAllMeetingsResponse, MeetingsGetAllMeetingsError, InfiniteData<MeetingsGetAllMeetingsResponse>, QueryKey<Options<MeetingsGetAllMeetingsData>>, number | Pick<QueryKey<Options<MeetingsGetAllMeetingsData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
    // @ts-ignore
    {
        queryFn: async ({ pageParam, queryKey, signal }) => {
            // @ts-ignore
            const page: Pick<QueryKey<Options<MeetingsGetAllMeetingsData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
                query: {
                    offset: pageParam
                }
            };
            const params = createInfiniteParams(queryKey, page);
            const { data } = await meetingsGetAllMeetings({
                ...options,
                ...params,
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: meetingsGetAllMeetingsInfiniteQueryKey(options)
    });
};

export const meetingsGetOngoingMeetingsQueryKey = (options: Options<MeetingsGetOngoingMeetingsData>) => createQueryKey('meetingsGetOngoingMeetings', options);

/**
 * Get Ongoing Meetings
 * 获取所有正在进行中的会议
 */
export const meetingsGetOngoingMeetingsOptions = (options: Options<MeetingsGetOngoingMeetingsData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await meetingsGetOngoingMeetings({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: meetingsGetOngoingMeetingsQueryKey(options)
    });
};

export const meetingsRequestRecordQueryKey = (options?: Options<MeetingsRequestRecordData>) => createQueryKey('meetingsRequestRecord', options);

/**
 * Request Record
 */
export const meetingsRequestRecordOptions = (options?: Options<MeetingsRequestRecordData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await meetingsRequestRecord({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: meetingsRequestRecordQueryKey(options)
    });
};

/**
 * Request Record
 */
export const meetingsRequestRecordMutation = (options?: Partial<Options<MeetingsRequestRecordData>>): UseMutationOptions<MeetingsRequestRecordResponse, MeetingsRequestRecordError, Options<MeetingsRequestRecordData>> => {
    const mutationOptions: UseMutationOptions<MeetingsRequestRecordResponse, MeetingsRequestRecordError, Options<MeetingsRequestRecordData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await meetingsRequestRecord({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const meetingsDownloadAudioQueryKey = (options: Options<MeetingsDownloadAudioData>) => createQueryKey('meetingsDownloadAudio', options);

/**
 * Download Audio
 */
export const meetingsDownloadAudioOptions = (options: Options<MeetingsDownloadAudioData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await meetingsDownloadAudio({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: meetingsDownloadAudioQueryKey(options)
    });
};

export const meetingsGetAudioQueryKey = (options: Options<MeetingsGetAudioData>) => createQueryKey('meetingsGetAudio', options);

/**
 * Get Audio
 */
export const meetingsGetAudioOptions = (options: Options<MeetingsGetAudioData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await meetingsGetAudio({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: meetingsGetAudioQueryKey(options)
    });
};