// This file is auto-generated by @hey-api/openapi-ts

import { type Options as ClientOptions, type TDataShape, type Client, urlSearchParamsBodySerializer, formDataBodySerializer } from './client';
import type { UsersLoginForAccessTokenData, UsersLoginForAccessTokenResponses, UsersLoginForAccessTokenErrors, UsersRegisterData, UsersRegisterResponses, UsersRegisterErrors, UsersLoginData, UsersLoginResponses, UsersLoginErrors, UsersCheckLoginData, UsersCheckLoginResponses, UsersCheckLoginErrors, UsersLogoutData, UsersLogoutResponses, UsersLogoutErrors, MeetingsStartMeetingData, MeetingsStartMeetingResponses, MeetingsStartMeetingErrors, MeetingsJoinMeetingData, MeetingsJoinMeetingResponses, MeetingsJoinMeetingErrors, MeetingsEndMeetingData, MeetingsEndMeetingResponses, MeetingsEndMeetingErrors, MeetingsLeaveMeetingData, MeetingsLeaveMeetingResponses, MeetingsLeaveMeetingErrors, MeetingsRequestTotalData, MeetingsRequestTotalResponses, MeetingsRequestTotalErrors, MeetingsChangeTitleData, MeetingsChangeTitleResponses, MeetingsChangeTitleErrors, MeetingsUpdateHotWordsData, MeetingsUpdateHotWordsResponses, MeetingsUpdateHotWordsErrors, MeetingsManualUpdateData, MeetingsManualUpdateResponses, MeetingsManualUpdateErrors, MeetingsChooseNodeData, MeetingsChooseNodeResponses, MeetingsChooseNodeErrors, MeetingsModifyNodeData, MeetingsModifyNodeResponses, MeetingsModifyNodeErrors, MeetingsAddNodeData, MeetingsAddNodeResponses, MeetingsAddNodeErrors, MeetingsDeleteNodeData, MeetingsDeleteNodeResponses, MeetingsDeleteNodeErrors, MeetingsSendUserSummaryData, MeetingsSendUserSummaryResponses, MeetingsSendUserSummaryErrors, MeetingsGetAllMeetingsData, MeetingsGetAllMeetingsResponses, MeetingsGetAllMeetingsErrors, MeetingsGetOngoingMeetingsData, MeetingsGetOngoingMeetingsResponses, MeetingsGetOngoingMeetingsErrors, MeetingsRequestRecordData, MeetingsRequestRecordResponses, MeetingsRequestRecordErrors, MeetingsDownloadAudioData, MeetingsDownloadAudioResponses, MeetingsDownloadAudioErrors, MeetingsGetAudioData, MeetingsGetAudioResponses, MeetingsGetAudioErrors } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Login For Access Token
 */
export const usersLoginForAccessToken = <ThrowOnError extends boolean = true>(options: Options<UsersLoginForAccessTokenData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<UsersLoginForAccessTokenResponses, UsersLoginForAccessTokenErrors, ThrowOnError>({
        ...urlSearchParamsBodySerializer,
        url: '/token',
        ...options,
        headers: {
            'Content-Type': 'application/x-www-form-urlencoded',
            ...options.headers
        }
    });
};

/**
 * Register
 */
export const usersRegister = <ThrowOnError extends boolean = true>(options: Options<UsersRegisterData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<UsersRegisterResponses, UsersRegisterErrors, ThrowOnError>({
        url: '/api/register',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Login
 */
export const usersLogin = <ThrowOnError extends boolean = true>(options: Options<UsersLoginData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<UsersLoginResponses, UsersLoginErrors, ThrowOnError>({
        url: '/api/login',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Check Login
 */
export const usersCheckLogin = <ThrowOnError extends boolean = true>(options?: Options<UsersCheckLoginData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<UsersCheckLoginResponses, UsersCheckLoginErrors, ThrowOnError>({
        url: '/api/checkLogin',
        ...options
    });
};

/**
 * Logout
 */
export const usersLogout = <ThrowOnError extends boolean = true>(options?: Options<UsersLogoutData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<UsersLogoutResponses, UsersLogoutErrors, ThrowOnError>({
        url: '/api/logout',
        ...options
    });
};

/**
 * Start Meeting
 */
export const meetingsStartMeeting = <ThrowOnError extends boolean = true>(options: Options<MeetingsStartMeetingData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<MeetingsStartMeetingResponses, MeetingsStartMeetingErrors, ThrowOnError>({
        url: '/api/meetingStart',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Join Meeting
 */
export const meetingsJoinMeeting = <ThrowOnError extends boolean = true>(options: Options<MeetingsJoinMeetingData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<MeetingsJoinMeetingResponses, MeetingsJoinMeetingErrors, ThrowOnError>({
        url: '/api/joinMeeting',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * End Meeting
 */
export const meetingsEndMeeting = <ThrowOnError extends boolean = true>(options?: Options<MeetingsEndMeetingData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<MeetingsEndMeetingResponses, MeetingsEndMeetingErrors, ThrowOnError>({
        url: '/api/meetingEnd',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Leave Meeting
 */
export const meetingsLeaveMeeting = <ThrowOnError extends boolean = true>(options?: Options<MeetingsLeaveMeetingData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<MeetingsLeaveMeetingResponses, MeetingsLeaveMeetingErrors, ThrowOnError>({
        url: '/api/leaveMeeting',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Request Total
 */
export const meetingsRequestTotal = <ThrowOnError extends boolean = true>(options?: Options<MeetingsRequestTotalData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<MeetingsRequestTotalResponses, MeetingsRequestTotalErrors, ThrowOnError>({
        url: '/api/requestTotal',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Change Title
 */
export const meetingsChangeTitle = <ThrowOnError extends boolean = true>(options: Options<MeetingsChangeTitleData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<MeetingsChangeTitleResponses, MeetingsChangeTitleErrors, ThrowOnError>({
        url: '/api/changeTitle',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Update Hot Words
 */
export const meetingsUpdateHotWords = <ThrowOnError extends boolean = true>(options: Options<MeetingsUpdateHotWordsData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<MeetingsUpdateHotWordsResponses, MeetingsUpdateHotWordsErrors, ThrowOnError>({
        url: '/api/updateHotWords',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Manual Update
 */
export const meetingsManualUpdate = <ThrowOnError extends boolean = true>(options?: Options<MeetingsManualUpdateData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<MeetingsManualUpdateResponses, MeetingsManualUpdateErrors, ThrowOnError>({
        url: '/api/manualUpdate',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Choose Node
 * {
 * "chosenNodeId": "full id"
 * "meeting_hash_id": "hash id",
 * }
 */
export const meetingsChooseNode = <ThrowOnError extends boolean = true>(options: Options<MeetingsChooseNodeData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<MeetingsChooseNodeResponses, MeetingsChooseNodeErrors, ThrowOnError>({
        url: '/api/chooseNode',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Modify Node
 * 前端->后端：
 * {
 * "meeting_hash_id": str,
 * "full_id": str,
 * "content": str
 * }
 */
export const meetingsModifyNode = <ThrowOnError extends boolean = true>(options: Options<MeetingsModifyNodeData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<MeetingsModifyNodeResponses, MeetingsModifyNodeErrors, ThrowOnError>({
        url: '/api/modifyNode',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Add Node
 * 前端
 * {
 * "type": "ISSUE" / "POSITION",
 * "father_id": "父节点的full id",
 * "content": "",
 * "meeting_hash_id": "",
 * "suggestion_id": ""
 * }
 * 后端
 * {
 * "code": 0,
 * "full_id": "这个节点的full id"
 * }
 */
export const meetingsAddNode = <ThrowOnError extends boolean = true>(options: Options<MeetingsAddNodeData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<MeetingsAddNodeResponses, MeetingsAddNodeErrors, ThrowOnError>({
        url: '/api/addNode',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Delete Node
 * 前端
 * {
 * "full_id": "",  # issue/position的full id
 * "meeting_hash_id": ""
 * }
 */
export const meetingsDeleteNode = <ThrowOnError extends boolean = true>(options: Options<MeetingsDeleteNodeData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<MeetingsDeleteNodeResponses, MeetingsDeleteNodeErrors, ThrowOnError>({
        url: '/api/deleteNode',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Send User Summary
 * {
 * "meeting_hash_id": "hash id",
 * "edit_history": "list"
 * }
 */
export const meetingsSendUserSummary = <ThrowOnError extends boolean = true>(options: Options<MeetingsSendUserSummaryData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<MeetingsSendUserSummaryResponses, MeetingsSendUserSummaryErrors, ThrowOnError>({
        ...formDataBodySerializer,
        url: '/api/sendUserSummary',
        ...options,
        headers: {
            'Content-Type': null,
            ...options.headers
        }
    });
};

/**
 * Get All Meetings
 * 输入
 * {
 * hash_id: hash_id,
 * title: title,
 * start_time: startTime,
 * }
 * 输出
 * type MeetingItem = {
 * id: number;
 * hash_id: number;
 * topic: string;
 * created_by: string;
 * created_time: string;
 * status: string;
 * master: string;
 * hot_words: string;
 * anlysisStatus: string;
 * };
 */
export const meetingsGetAllMeetings = <ThrowOnError extends boolean = true>(options?: Options<MeetingsGetAllMeetingsData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<MeetingsGetAllMeetingsResponses, MeetingsGetAllMeetingsErrors, ThrowOnError>({
        url: '/api/getAllMeetings',
        ...options
    });
};

/**
 * Get Ongoing Meetings
 * 获取所有正在进行中的会议
 */
export const meetingsGetOngoingMeetings = <ThrowOnError extends boolean = true>(options: Options<MeetingsGetOngoingMeetingsData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<MeetingsGetOngoingMeetingsResponses, MeetingsGetOngoingMeetingsErrors, ThrowOnError>({
        url: '/api/ongoingMeetings',
        ...options
    });
};

/**
 * Request Record
 */
export const meetingsRequestRecord = <ThrowOnError extends boolean = true>(options?: Options<MeetingsRequestRecordData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<MeetingsRequestRecordResponses, MeetingsRequestRecordErrors, ThrowOnError>({
        url: '/api/requestRecord',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Download Audio
 */
export const meetingsDownloadAudio = <ThrowOnError extends boolean = true>(options: Options<MeetingsDownloadAudioData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<MeetingsDownloadAudioResponses, MeetingsDownloadAudioErrors, ThrowOnError>({
        url: '/api/downloadAudio/{meeting_id}',
        ...options
    });
};

/**
 * Get Audio
 */
export const meetingsGetAudio = <ThrowOnError extends boolean = true>(options: Options<MeetingsGetAudioData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<MeetingsGetAudioResponses, MeetingsGetAudioErrors, ThrowOnError>({
        url: '/audio/{meeting_id}',
        ...options
    });
};