// This file is auto-generated by @hey-api/openapi-ts

/**
 * AddNodeResponse
 */
export type AddNodeResponse = {
    /**
     * Code
     */
    code?: 0;
    /**
     * Full Id
     */
    full_id: string;
};

/**
 * Argument
 */
export type Argument = {
    /**
     * Full Id
     */
    full_id: string;
    /**
     * Content
     */
    content: string;
    /**
     * Type
     */
    type?: 'confirmed' | 'deleted' | 'unconfirmed';
    /**
     * Argument Id
     */
    argument_id: string;
    /**
     * Ref
     */
    ref?: string | null;
};

/**
 * AsrSentence
 */
export type AsrSentence = {
    /**
     * Content
     */
    content: string;
    /**
     * Time Range
     */
    time_range: Array<number>;
    /**
     * Speaker Id
     */
    speaker_id: string;
};

/**
 * Body_meetings-add_node
 */
export type BodyMeetingsAddNode = {
    /**
     * Type
     */
    type: 'ISSUE' | 'POSITION';
    /**
     * Father Id
     */
    father_id: string;
    /**
     * Content
     */
    content: string;
    /**
     * Meeting Id
     */
    meeting_id?: string | null;
    /**
     * Meeting Hash Id
     */
    meeting_hash_id?: string | null;
};

/**
 * Body_meetings-change_title
 */
export type BodyMeetingsChangeTitle = {
    /**
     * Title
     */
    title: string;
    /**
     * Meeting Id
     */
    meeting_id?: string | null;
    /**
     * Meeting Hash Id
     */
    meeting_hash_id?: string | null;
};

/**
 * Body_meetings-choose_node
 */
export type BodyMeetingsChooseNode = {
    /**
     * Chosennodeid
     */
    chosenNodeId: string;
    /**
     * Meeting Id
     */
    meeting_id?: string | null;
    /**
     * Meeting Hash Id
     */
    meeting_hash_id?: string | null;
};

/**
 * Body_meetings-delete_node
 */
export type BodyMeetingsDeleteNode = {
    /**
     * Full Id
     */
    full_id: string;
    /**
     * Meeting Id
     */
    meeting_id?: string | null;
    /**
     * Meeting Hash Id
     */
    meeting_hash_id?: string | null;
};

/**
 * Body_meetings-end_meeting
 */
export type BodyMeetingsEndMeeting = {
    /**
     * Meeting Id
     */
    meeting_id?: string | null;
    /**
     * Meeting Hash Id
     */
    meeting_hash_id?: string | null;
};

/**
 * Body_meetings-join_meeting
 */
export type BodyMeetingsJoinMeeting = {
    /**
     * Nickname
     */
    nickname: string;
    /**
     * Meeting Id
     */
    meeting_id?: string | null;
    /**
     * Meeting Hash Id
     */
    meeting_hash_id?: string | null;
};

/**
 * Body_meetings-leave_meeting
 */
export type BodyMeetingsLeaveMeeting = {
    /**
     * Meeting Id
     */
    meeting_id?: string | null;
    /**
     * Meeting Hash Id
     */
    meeting_hash_id?: string | null;
};

/**
 * Body_meetings-manual_update
 */
export type BodyMeetingsManualUpdate = {
    /**
     * Meeting Id
     */
    meeting_id?: string | null;
    /**
     * Meeting Hash Id
     */
    meeting_hash_id?: string | null;
};

/**
 * Body_meetings-modify_node
 */
export type BodyMeetingsModifyNode = {
    /**
     * Full Id
     */
    full_id: string;
    /**
     * Content
     */
    content: string;
    /**
     * Meeting Id
     */
    meeting_id?: string | null;
    /**
     * Meeting Hash Id
     */
    meeting_hash_id?: string | null;
};

/**
 * Body_meetings-request_record
 */
export type BodyMeetingsRequestRecord = {
    /**
     * Meeting Id
     */
    meeting_id?: string | null;
    /**
     * Meeting Hash Id
     */
    meeting_hash_id?: string | null;
};

/**
 * Body_meetings-request_total
 */
export type BodyMeetingsRequestTotal = {
    /**
     * Meeting Id
     */
    meeting_id?: string | null;
    /**
     * Meeting Hash Id
     */
    meeting_hash_id?: string | null;
};

/**
 * Body_meetings-send_user_summary
 */
export type BodyMeetingsSendUserSummary = {
    /**
     * Edit History
     */
    edit_history: Array<unknown>;
    /**
     * Meeting Id
     */
    meeting_id?: string | null;
    /**
     * Meeting Hash Id
     */
    meeting_hash_id?: string | null;
};

/**
 * Body_meetings-update_hot_words
 */
export type BodyMeetingsUpdateHotWords = {
    /**
     * Hot Words
     */
    hot_words: Array<string>;
    /**
     * Meeting Id
     */
    meeting_id?: string | null;
    /**
     * Meeting Hash Id
     */
    meeting_hash_id?: string | null;
};

/**
 * Body_users-login_for_access_token
 */
export type BodyUsersLoginForAccessToken = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
};

/**
 * Code
 */
export type Code = 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11;

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * InvalidNodeResponse
 */
export type InvalidNodeResponse = {
    /**
     * Code
     */
    code?: 6;
};

/**
 * Issue
 */
export type Issue = {
    /**
     * Full Id
     */
    full_id: string;
    /**
     * Content
     */
    content: string;
    /**
     * Type
     */
    type?: 'confirmed' | 'deleted' | 'unconfirmed';
    /**
     * Issue Id
     */
    issue_id: number;
    /**
     * Positions
     */
    positions: Array<Position>;
    source?: Relation | null;
};

/**
 * LoginResponse
 */
export type LoginResponse = {
    /**
     * Code
     */
    code: 0 | 9 | 8;
};

/**
 * MeetingItem
 */
export type MeetingItem = {
    /**
     * Id
     */
    id: string;
    /**
     * Hash Id
     */
    hash_id: string;
    /**
     * Topic
     */
    topic: string;
    /**
     * Create Time
     */
    create_time: string;
    /**
     * Create By
     */
    create_by: string;
    /**
     * Hotwords
     */
    hotwords: Array<string> | null;
    /**
     * Status
     */
    status: 'processing' | 'finished';
    /**
     * Master
     */
    master: string;
    /**
     * Meeting Language
     */
    meeting_language: 'Chinese' | 'English';
};

/**
 * MeetingJoinResponse
 */
export type MeetingJoinResponse = {
    /**
     * Code
     */
    code?: 0;
    /**
     * Meeting Id
     */
    meeting_id: string;
    /**
     * Meeting Hash Id
     */
    meeting_hash_id: string;
    /**
     * Topic
     */
    topic: string;
};

/**
 * MeetingLeaveResponse
 */
export type MeetingLeaveResponse = {
    /**
     * Code
     */
    code: 0 | 1;
};

/**
 * MeetingListResponse
 */
export type MeetingListResponse = {
    code: Code;
    /**
     * Meetings
     */
    meetings: Array<MeetingItem>;
    /**
     * Total
     */
    total: number;
};

/**
 * MeetingStart
 */
export type MeetingStart = {
    /**
     * Topic
     */
    topic: string;
    /**
     * Nickname
     */
    nickname: string;
    /**
     * Hotwords
     */
    hotwords?: Array<string> | null;
    /**
     * Meeting Resume Hash Id
     */
    meeting_resume_hash_id: string;
    /**
     * Type
     */
    type: 'graph' | 'document';
    /**
     * Meeting Language
     */
    meeting_language: 'Chinese' | 'English';
};

/**
 * MeetingStartResponse
 */
export type MeetingStartResponse = {
    /**
     * Code
     */
    code?: 0;
    /**
     * Meeting Id
     */
    meeting_id: string;
    /**
     * Meeting Hash Id
     */
    meeting_hash_id: string;
};

/**
 * MeetingStopResponse
 */
export type MeetingStopResponse = {
    /**
     * Code
     */
    code: 0 | 1;
};

/**
 * NotMeetingHostResponse
 */
export type NotMeetingHostResponse = {
    /**
     * Code
     */
    code?: 2;
};

/**
 * Position
 */
export type Position = {
    /**
     * Full Id
     */
    full_id: string;
    /**
     * Content
     */
    content: string;
    /**
     * Type
     */
    type?: 'confirmed' | 'deleted' | 'unconfirmed';
    /**
     * Position Id
     */
    position_id: number;
    /**
     * Ref
     */
    ref?: string | null;
    /**
     * Pros
     */
    pros: Array<Argument>;
    /**
     * Cons
     */
    cons: Array<Argument>;
    /**
     * Note
     */
    note?: string | null;
    /**
     * Generated Issue
     */
    generated_issue?: boolean;
};

/**
 * RegisterRequest
 */
export type RegisterRequest = {
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
};

/**
 * RegisterResponse
 */
export type RegisterResponse = {
    /**
     * Code
     */
    code: 0 | 10 | 11;
};

/**
 * Relation
 */
export type Relation = {
    /**
     * Target Id
     */
    target_id: string;
    /**
     * Target Type
     */
    target_type: string;
    /**
     * Target Content
     */
    target_content: string;
    /**
     * Content
     */
    content: string;
};

/**
 * SuccessResponse
 */
export type SuccessResponse = {
    /**
     * Code
     */
    code?: 0;
};

/**
 * Token
 */
export type Token = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type: string;
};

/**
 * TotalData
 */
export type TotalData = {
    /**
     * Speaker
     */
    speaker: {
        [key: string]: string;
    };
    /**
     * Sentences
     */
    sentences: Array<AsrSentence>;
    /**
     * Meeting Id
     */
    meeting_id: string;
    /**
     * Meeting Hash Id
     */
    meeting_hash_id: string;
    /**
     * Topic
     */
    topic: string;
    /**
     * Role
     */
    role: 'host' | 'participant';
    /**
     * Ai Type
     */
    ai_type: 'graph' | 'document';
    /**
     * Issue Map
     */
    issue_map: Array<Issue>;
};

/**
 * UserResponse
 */
export type UserResponse = {
    /**
     * Code
     */
    code?: 0;
    /**
     * Username
     */
    username: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

/**
 * WrongAgentResponse
 */
export type WrongAgentResponse = {
    /**
     * Code
     */
    code?: 5;
};

export type UsersLoginForAccessTokenData = {
    body: BodyUsersLoginForAccessToken;
    path?: never;
    query?: never;
    url: '/token';
};

export type UsersLoginForAccessTokenErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersLoginForAccessTokenError = UsersLoginForAccessTokenErrors[keyof UsersLoginForAccessTokenErrors];

export type UsersLoginForAccessTokenResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type UsersLoginForAccessTokenResponse = UsersLoginForAccessTokenResponses[keyof UsersLoginForAccessTokenResponses];

export type UsersRegisterData = {
    body: RegisterRequest;
    path?: never;
    query?: never;
    url: '/api/register';
};

export type UsersRegisterErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersRegisterError = UsersRegisterErrors[keyof UsersRegisterErrors];

export type UsersRegisterResponses = {
    /**
     * Successful Response
     */
    200: RegisterResponse;
};

export type UsersRegisterResponse = UsersRegisterResponses[keyof UsersRegisterResponses];

export type UsersLoginData = {
    body: RegisterRequest;
    path?: never;
    query?: never;
    url: '/api/login';
};

export type UsersLoginErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersLoginError = UsersLoginErrors[keyof UsersLoginErrors];

export type UsersLoginResponses = {
    /**
     * Successful Response
     */
    200: LoginResponse;
};

export type UsersLoginResponse = UsersLoginResponses[keyof UsersLoginResponses];

export type UsersCheckLoginData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/checkLogin';
};

export type UsersCheckLoginErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersCheckLoginError = UsersCheckLoginErrors[keyof UsersCheckLoginErrors];

export type UsersCheckLoginResponses = {
    /**
     * Successful Response
     */
    200: UserResponse;
};

export type UsersCheckLoginResponse = UsersCheckLoginResponses[keyof UsersCheckLoginResponses];

export type UsersLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/logout';
};

export type UsersLogoutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersLogoutError = UsersLogoutErrors[keyof UsersLogoutErrors];

export type UsersLogoutResponses = {
    /**
     * Successful Response
     */
    200: SuccessResponse;
};

export type UsersLogoutResponse = UsersLogoutResponses[keyof UsersLogoutResponses];

export type MeetingsStartMeetingData = {
    body: MeetingStart;
    path?: never;
    query?: never;
    url: '/api/meetingStart';
};

export type MeetingsStartMeetingErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type MeetingsStartMeetingError = MeetingsStartMeetingErrors[keyof MeetingsStartMeetingErrors];

export type MeetingsStartMeetingResponses = {
    /**
     * Successful Response
     */
    200: MeetingStartResponse;
};

export type MeetingsStartMeetingResponse = MeetingsStartMeetingResponses[keyof MeetingsStartMeetingResponses];

export type MeetingsJoinMeetingData = {
    body: BodyMeetingsJoinMeeting;
    path?: never;
    query?: never;
    url: '/api/joinMeeting';
};

export type MeetingsJoinMeetingErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type MeetingsJoinMeetingError = MeetingsJoinMeetingErrors[keyof MeetingsJoinMeetingErrors];

export type MeetingsJoinMeetingResponses = {
    /**
     * Successful Response
     */
    200: MeetingJoinResponse;
};

export type MeetingsJoinMeetingResponse = MeetingsJoinMeetingResponses[keyof MeetingsJoinMeetingResponses];

export type MeetingsEndMeetingData = {
    body?: BodyMeetingsEndMeeting;
    path?: never;
    query?: never;
    url: '/api/meetingEnd';
};

export type MeetingsEndMeetingErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type MeetingsEndMeetingError = MeetingsEndMeetingErrors[keyof MeetingsEndMeetingErrors];

export type MeetingsEndMeetingResponses = {
    /**
     * Response Meetings-End Meeting
     * Successful Response
     */
    200: MeetingStopResponse | NotMeetingHostResponse;
};

export type MeetingsEndMeetingResponse = MeetingsEndMeetingResponses[keyof MeetingsEndMeetingResponses];

export type MeetingsLeaveMeetingData = {
    body?: BodyMeetingsLeaveMeeting;
    path?: never;
    query?: never;
    url: '/api/leaveMeeting';
};

export type MeetingsLeaveMeetingErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type MeetingsLeaveMeetingError = MeetingsLeaveMeetingErrors[keyof MeetingsLeaveMeetingErrors];

export type MeetingsLeaveMeetingResponses = {
    /**
     * Successful Response
     */
    200: MeetingLeaveResponse;
};

export type MeetingsLeaveMeetingResponse = MeetingsLeaveMeetingResponses[keyof MeetingsLeaveMeetingResponses];

export type MeetingsRequestTotalData = {
    body?: BodyMeetingsRequestTotal;
    path?: never;
    query?: never;
    url: '/api/requestTotal';
};

export type MeetingsRequestTotalErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type MeetingsRequestTotalError = MeetingsRequestTotalErrors[keyof MeetingsRequestTotalErrors];

export type MeetingsRequestTotalResponses = {
    /**
     * Successful Response
     */
    200: TotalData;
};

export type MeetingsRequestTotalResponse = MeetingsRequestTotalResponses[keyof MeetingsRequestTotalResponses];

export type MeetingsChangeTitleData = {
    body: BodyMeetingsChangeTitle;
    path?: never;
    query?: never;
    url: '/api/changeTitle';
};

export type MeetingsChangeTitleErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type MeetingsChangeTitleError = MeetingsChangeTitleErrors[keyof MeetingsChangeTitleErrors];

export type MeetingsChangeTitleResponses = {
    /**
     * Response Meetings-Change Title
     * Successful Response
     */
    200: SuccessResponse | NotMeetingHostResponse;
};

export type MeetingsChangeTitleResponse = MeetingsChangeTitleResponses[keyof MeetingsChangeTitleResponses];

export type MeetingsUpdateHotWordsData = {
    body: BodyMeetingsUpdateHotWords;
    path?: never;
    query?: never;
    url: '/api/updateHotWords';
};

export type MeetingsUpdateHotWordsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type MeetingsUpdateHotWordsError = MeetingsUpdateHotWordsErrors[keyof MeetingsUpdateHotWordsErrors];

export type MeetingsUpdateHotWordsResponses = {
    /**
     * Response Meetings-Update Hot Words
     * Successful Response
     */
    200: SuccessResponse | NotMeetingHostResponse;
};

export type MeetingsUpdateHotWordsResponse = MeetingsUpdateHotWordsResponses[keyof MeetingsUpdateHotWordsResponses];

export type MeetingsManualUpdateData = {
    body?: BodyMeetingsManualUpdate;
    path?: never;
    query?: never;
    url: '/api/manualUpdate';
};

export type MeetingsManualUpdateErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type MeetingsManualUpdateError = MeetingsManualUpdateErrors[keyof MeetingsManualUpdateErrors];

export type MeetingsManualUpdateResponses = {
    /**
     * Response Meetings-Manual Update
     * Successful Response
     */
    200: SuccessResponse | WrongAgentResponse;
};

export type MeetingsManualUpdateResponse = MeetingsManualUpdateResponses[keyof MeetingsManualUpdateResponses];

export type MeetingsChooseNodeData = {
    body: BodyMeetingsChooseNode;
    path?: never;
    query?: never;
    url: '/api/chooseNode';
};

export type MeetingsChooseNodeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type MeetingsChooseNodeError = MeetingsChooseNodeErrors[keyof MeetingsChooseNodeErrors];

export type MeetingsChooseNodeResponses = {
    /**
     * Response Meetings-Choose Node
     * Successful Response
     */
    200: SuccessResponse | WrongAgentResponse;
};

export type MeetingsChooseNodeResponse = MeetingsChooseNodeResponses[keyof MeetingsChooseNodeResponses];

export type MeetingsModifyNodeData = {
    body: BodyMeetingsModifyNode;
    path?: never;
    query?: never;
    url: '/api/modifyNode';
};

export type MeetingsModifyNodeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type MeetingsModifyNodeError = MeetingsModifyNodeErrors[keyof MeetingsModifyNodeErrors];

export type MeetingsModifyNodeResponses = {
    /**
     * Response Meetings-Modify Node
     * Successful Response
     */
    200: SuccessResponse | WrongAgentResponse;
};

export type MeetingsModifyNodeResponse = MeetingsModifyNodeResponses[keyof MeetingsModifyNodeResponses];

export type MeetingsAddNodeData = {
    body: BodyMeetingsAddNode;
    path?: never;
    query?: never;
    url: '/api/addNode';
};

export type MeetingsAddNodeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type MeetingsAddNodeError = MeetingsAddNodeErrors[keyof MeetingsAddNodeErrors];

export type MeetingsAddNodeResponses = {
    /**
     * Response Meetings-Add Node
     * Successful Response
     */
    200: AddNodeResponse | InvalidNodeResponse | WrongAgentResponse;
};

export type MeetingsAddNodeResponse = MeetingsAddNodeResponses[keyof MeetingsAddNodeResponses];

export type MeetingsDeleteNodeData = {
    body: BodyMeetingsDeleteNode;
    path?: never;
    query?: never;
    url: '/api/deleteNode';
};

export type MeetingsDeleteNodeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type MeetingsDeleteNodeError = MeetingsDeleteNodeErrors[keyof MeetingsDeleteNodeErrors];

export type MeetingsDeleteNodeResponses = {
    /**
     * Response Meetings-Delete Node
     * Successful Response
     */
    200: SuccessResponse | WrongAgentResponse;
};

export type MeetingsDeleteNodeResponse = MeetingsDeleteNodeResponses[keyof MeetingsDeleteNodeResponses];

export type MeetingsSendUserSummaryData = {
    body: BodyMeetingsSendUserSummary;
    path?: never;
    query?: never;
    url: '/api/sendUserSummary';
};

export type MeetingsSendUserSummaryErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type MeetingsSendUserSummaryError = MeetingsSendUserSummaryErrors[keyof MeetingsSendUserSummaryErrors];

export type MeetingsSendUserSummaryResponses = {
    /**
     * Response Meetings-Send User Summary
     * Successful Response
     */
    200: SuccessResponse | WrongAgentResponse;
};

export type MeetingsSendUserSummaryResponse = MeetingsSendUserSummaryResponses[keyof MeetingsSendUserSummaryResponses];

export type MeetingsGetAllMeetingsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Offset
         */
        offset?: number;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Hash Id
         */
        hash_id?: string | null;
        /**
         * Title
         */
        title?: string | null;
        /**
         * Start Time
         */
        start_time?: string | null;
    };
    url: '/api/getAllMeetings';
};

export type MeetingsGetAllMeetingsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type MeetingsGetAllMeetingsError = MeetingsGetAllMeetingsErrors[keyof MeetingsGetAllMeetingsErrors];

export type MeetingsGetAllMeetingsResponses = {
    /**
     * Successful Response
     */
    200: MeetingListResponse;
};

export type MeetingsGetAllMeetingsResponse = MeetingsGetAllMeetingsResponses[keyof MeetingsGetAllMeetingsResponses];

export type MeetingsGetOngoingMeetingsData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Limit
         */
        limit: number;
    };
    url: '/api/ongoingMeetings';
};

export type MeetingsGetOngoingMeetingsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type MeetingsGetOngoingMeetingsError = MeetingsGetOngoingMeetingsErrors[keyof MeetingsGetOngoingMeetingsErrors];

export type MeetingsGetOngoingMeetingsResponses = {
    /**
     * Successful Response
     */
    200: MeetingListResponse;
};

export type MeetingsGetOngoingMeetingsResponse = MeetingsGetOngoingMeetingsResponses[keyof MeetingsGetOngoingMeetingsResponses];

export type MeetingsRequestRecordData = {
    body?: BodyMeetingsRequestRecord;
    path?: never;
    query?: never;
    url: '/api/requestRecord';
};

export type MeetingsRequestRecordErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type MeetingsRequestRecordError = MeetingsRequestRecordErrors[keyof MeetingsRequestRecordErrors];

export type MeetingsRequestRecordResponses = {
    /**
     * Successful Response
     */
    200: TotalData;
};

export type MeetingsRequestRecordResponse = MeetingsRequestRecordResponses[keyof MeetingsRequestRecordResponses];

export type MeetingsDownloadAudioData = {
    body?: never;
    path: {
        /**
         * Meeting Id
         */
        meeting_id: string;
    };
    query?: never;
    url: '/api/downloadAudio/{meeting_id}';
};

export type MeetingsDownloadAudioErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type MeetingsDownloadAudioError = MeetingsDownloadAudioErrors[keyof MeetingsDownloadAudioErrors];

export type MeetingsDownloadAudioResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type MeetingsGetAudioData = {
    body?: never;
    headers?: {
        /**
         * Range
         */
        range?: string | null;
    };
    path: {
        /**
         * Meeting Id
         */
        meeting_id: string;
    };
    query?: never;
    url: '/audio/{meeting_id}';
};

export type MeetingsGetAudioErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type MeetingsGetAudioError = MeetingsGetAudioErrors[keyof MeetingsGetAudioErrors];

export type MeetingsGetAudioResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ClientOptions = {
    baseUrl: `${string}://openapi.json` | (string & {});
};